---
title: Dominant tree species in valley-wide plots at Hubbard Brook Experimental Forest,
  Woodstock, NH.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE )

library(tidyverse)
library(ggpubr)
library(cowplot)
library(ggmap)
library(maps)
library(mapdata)
library(ggsn)
library(plotly)
library(rgdal)
library(raster)


trees=read.csv("~/Documents/Things/HBR_map/valley_tree_inventory.txt", header=TRUE)%>%
  dplyr::select(PLOT, UTM_EASTING, UTM_NORTHING, SPECIES, DBH) %>%
  group_by(PLOT, SPECIES) %>%
  mutate(Total_DBH=sum(DBH)) %>% 
  ungroup() %>% 
  group_by(PLOT) %>% 
  mutate(max_DBH=max(Total_DBH)) %>% 
  filter(Total_DBH==max_DBH) %>% 
  slice(1)

utmpoints=trees %>% 
  dplyr::select(UTM_EASTING,UTM_NORTHING)

utm1 <- data.frame(x=utmpoints$UTM_EASTING,y=utmpoints$UTM_NORTHING) 
coordinates(utm1) <- ~x+y 
class(utm1)
proj4string(utm1) <- CRS("+proj=utm +zone=19 +datum=WGS84 +units=m +ellps=WGS84") 
utm2 <- spTransform(utm1,CRS("+proj=longlat +datum=WGS84"))
utm_df=data.frame(utm2)

# ggplot()+geom_point(data=utm_df, aes(x=UTM_EASTING, y=UTM_NORTHING, group=NULL), colour="springgreen", size=5)
# 

utm_df$PLOT=trees$PLOT

soil_chem=read.csv("~/Documents/Things/HBR_map/valley_soil_chem.txt", header=TRUE)

plots=trees %>% 
  left_join(utm_df, by="PLOT") %>% 
  mutate(Species=case_when(SPECIES=="AB" ~ "American beech",
                           SPECIES=="BF" ~ "Balsam fir",
                           SPECIES=="EH" ~ "Eastern hemlock",
                           SPECIES=="PB" ~ "Paper birch",
                           SPECIES=="PC" ~ "Pin cherry",
                           SPECIES=="RM" ~ "Red maple",
                           SPECIES=="RS" ~ "Red spruce",
                           SPECIES=="SM" ~ "Sugar maple",
                           SPECIES=="STM" ~ "Striped maple",
                           SPECIES=="WA" ~ "White ash",
                           SPECIES=="YB" ~ "Yellow birch")) %>% 
  left_join(soil_chem, by="PLOT") %>% 
  rename(Moisture=MOISTURE_.,
         pH=PH,
         Percent_organic_matter=OM_.)


#Next steps: add the soil characteristics

```


***  


```{r Speciesmap, fig.width=12}
closeUpmap=ggplot(data=nh)+
  geom_polygon(aes(x=long, y=lat, group=group), fill="gray94", color="black")+
  coord_fixed(xlim = c(-71.8, -71.7),  ylim = c(43.915, 43.962), ratio=1.3)+
  geom_point(aes(x = x, y = y, colour=Species, label=pH, label2=Percent_organic_matter, label3=Moisture), data = plots, size = 3)+
  scale_colour_viridis_d()+
  ggtitle("Dominant tree species in valley-wide plots")+
  labs(x="Hover over any point for information about the soil chemistry", y= " ")
  # geom_text(data = plots, aes(x = x, y = y, label = SPECIES), size = 3, vjust = 1.5, hjust = 0.5, colour="black")
  #scalebar(x.min=276000, x.max=283000, y.min=48663000, y.max=48712000, dist = 10, dist_unit = "km", model = "WGS84", transform=TRUE)

ggplotly(closeUpmap)

```

***  


```{r omMap, fig.width=12}
plots.remove.na=plots %>% 
  drop_na() %>% 
  filter(EXCH_Ca > 0)

pH=ggplot(data=nh)+
  geom_polygon(aes(x=long, y=lat, group=group), fill="gray94", color="black")+
  coord_fixed(xlim = c(-71.8, -71.7),  ylim = c(43.915, 43.962), ratio=1.3)+
  geom_point(aes(x = x, y = y, colour=pH), data = plots.remove.na, size = 5)+
  scale_colour_viridis_c()+
  ggtitle("Soil pH")+
  labs(x= "Longitude", y="Latitude" )

pH


```

***  

```{r calciumMap, fig.width=12}

calcium=ggplot(data=nh)+
  geom_polygon(aes(x=long, y=lat, group=group), fill="gray94", color="black")+
  coord_fixed(xlim = c(-71.8, -71.7),  ylim = c(43.915, 43.962), ratio=1.3)+
  geom_point(aes(x = x, y = y, colour=EXCH_Ca), data = plots.remove.na, size = 5)+
  scale_colour_viridis_c()+
  ggtitle("Exchangeable Calcium")+
  labs(x= "Longitude", y="Latitude" )

calcium


```

***  


```{r NHmap, fig.width=12}
states <- map_data("state")
nh <- subset(states, region %in% c("new hampshire"))

regionalmap=ggplot(data=nh)+
  geom_polygon(aes(x=long, y=lat, group=group), fill="darkseagreen3", color="black")+
  coord_fixed(1.3)+
  theme(axis.text=element_blank(), axis.line = element_blank(), axis.ticks=element_blank(), axis.title=element_blank())+
    geom_text(x=-71.75, y=43.93, label="*\nHubbard Brook", size=6)

 
regionalmap


```
